version: 2

snapshot:
  version_template: "dev-{{ .ShortCommit }}"

before:
  hooks:
    - go generate ./...
    - go mod tidy

builds:
  - id: ctp-auth-sso
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X {{.ModulePath}}/meta.Version={{.Version}} -X {{.ModulePath}}/meta.Commit={{.Commit}} -X {{.ModulePath}}/meta.BuildDate={{.Date}}

dockers_v2:
  - id: ctp-auth-sso
    ids:
      - ctp-auth-sso
    disable: "{{ .IsSnapshot }}"
    dockerfile: Dockerfile
    extra_files:
      - templates/
      - static/
      - favicon.ico
    images:
      - ghcr.io/vatsimnetwork/ctp-auth-sso
    tags:
      - "{{ .Version }}"
      - "latest"
    platforms:
      - linux/amd64